### ISSUE TITLE
Consider appending build metadata rather than a prerelease

### ISSUE THREAD

**Issue by rowanmanning** [quarterto/heroku-version-infer#7]
In [Semver 2](https://semver.org/), there's a difference in semantics between a prerelease and build metadata (this distinction didn't exist in Semver 1). I'm proposing that we append build metadata rather than a prerelease. Why, you ask?

Well mostly for the app I'm working on to be able to determine whether a version is a prerelease, and thus considered unstable or in a beta state. We have versions of some components or services which have prereleases like `1.0.0-0` and there's not really a way I can differentiate between these "unstable" prereleases, and the random hash prereleases on our services that are auto-versioned.

I think the docs kind of back this up:

This is a prerelease: `1.0.0-abc123`, the documentation states:
> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version

This is build metadata: `1.0.0+abc123`, the documentation states:
>  Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

(I'm also happy for this to be an option or flag, might be better as we wouldn't have to bump major)

**Comment by apaleslimghost** [comment]
TIL. sounds good. i'd prefer not a flag to keep things simple, so let's make this a major version. knowing you, you've already got a PR ready to go, right? 😉

**Comment by rowanmanning** [comment]
I _did_, but then I read this and just wanted to check that this doesn't trip you up at all?
https://github.com/npm/npm/issues/12825#issuecomment-221434934

**Comment by apaleslimghost** [comment]
ah, that's going to trip _everyone_ up https://github.com/quarterto/git-version-infer/blob/master/bin.js#L64

**Comment by rowanmanning** [comment]
🤔 not sure what to do here then. I know you're not keen on flags, but would you be adverse to me allowing removal of the SHA after the version? The way we're using this (just a count of commit messages and no review apps) means it'd be safe to in our case
